---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(web)"
      prefix-development: "chore(web-dev)"

  - package-ecosystem: "npm"
    directory: "/api/v1"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(api-v1)"
      prefix-development: "chore(api-v1-dev)"

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(web-docker)"

  - package-ecosystem: "docker"
    directory: "/api/v1"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(api-v1-docker)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
