---
services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  fair-share:
    image: ghcr.io/elidholm/fair-share
    container_name: fair-share
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Mounts the current directory into the container's /app for live updates
      - /app/node_modules  # Ensures node_modules is isolated inside the container
