---
services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=elidholm@fairshare.fun"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  fairshare:
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fairshare.rule=Host(`fairshare.fun`)"
      - "traefik.http.routers.fairshare.entrypoints=websecure"
      - "traefik.http.routers.fairshare.tls.certresolver=myresolver"
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules  # Ensures node_modules is isolated inside the container
      - ./frontend/src:/app/src

volumes:
  letsencrypt:
