---
services:
  traefik:
    image: traefik:v3.1
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=elidholm@fairshare.fun"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
      - mode: host
        protocol: tcp
        target: 443
        published: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  web:
    image: ghcr.io/elidholm/fairshare-web:${GIT_COMMIT_HASH:-latest}
    environment:
      - NODE_ENV=production
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fairshare_web.rule=Host(`fairshare.fun`)"
        - "traefik.http.routers.fairshare_web.entrypoints=websecure"
        - "traefik.http.routers.fairshare_web.tls.certresolver=myresolver"
        - "traefik.http.routers.fairshare_web.service=fairshare_web"
        - "traefik.http.services.fairshare_web.loadbalancer.server.port=3000"
      update_config:
        order: start-first
      replicas: 3
    depends_on:
      - api_v1

  api_v1:
    image: ghcr.io/elidholm/fairshare-api-v1:${GIT_COMMIT_HASH:-latest}
    volumes:
      - /cm/storage/fairshare:/app/database/
    environment:
      - DB_TYPE=sqlite
      - DB_PATH=/app/database/fairshare.db
      - NODE_ENV=production

volumes:
  letsencrypt:
