---
services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DB_TYPE=sqlite
      - DB_PATH=/app/database/fairshare.db
      - NODE_ENV=development
    ports:
      - "3001:3001"
    volumes:
      - ./local_db:/app/database/
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
