---
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - "--cleanup"
      - "--label-enable"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - web

  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=elidholm@fairshare.fun"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - web

  frontend:
    image: ghcr.io/elidholm/fairshare-frontend:master
    container_name: frontend
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fairshare.rule=Host(`fairshare.fun`)"
      - "traefik.http.routers.fairshare.entrypoints=websecure"
      - "traefik.http.routers.fairshare.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - backend
      - traefik
    networks:
      - web

  backend:
    image: ghcr.io/elidholm/fairshare-backend:master
    container_name: backend
    volumes:
      - /cm/storage/fairshare:/app/database/
    environment:
      - DB_TYPE=sqlite
      - DB_PATH=/app/database/fairshare.db
      - NODE_ENV=production
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web

volumes:
  letsencrypt:

networks:
  web:
    driver: bridge
