version: '3.8'

services:
  fair-share:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20  # Matches the ARG in the Dockerfile, can be changed as needed
    ports:
      - "5173:5173"  # Maps port 5173 on the host to port 5173 in the container
    environment:
      NODE_ENV: development
    volumes:
      - .:/app  # Mounts the current directory into the container's /app for live updates
      - /app/node_modules  # Ensures node_modules is isolated inside the container
    command: ["npm", "run", "dev"]
