---
services:
  fair-share:
    image: ghcr.io/elidholm/fair-share
    container_name: fair-share
    ports:
      - 8080:8080
    volumes:
      - .:/app  # Mounts the current directory into the container's /app for live updates
      - /app/node_modules  # Ensures node_modules is isolated inside the container
