---
name: CI Pipeline

on: [push]

jobs:
  frontend-ci:
    name: Frontend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests (Vitest)
        run: npm test

      - name: Build production bundle
        run: npm run build

  shellcheck:
    name: Shell Script Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  hadolint:
    name: Dockerfile Linting
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Hadolint
        run: hadolint ./**/*Dockerfile*
